name: 构建镜像并推送

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
    - name: 签出仓库
      uses: actions/checkout@v3
         
    - name: 登录DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: 制作镜像并上传
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.IMAGE }}
        build-args: |
          PORT=${{ vars.PORT }}
          USERNAME=${{ vars.USERNAME }}
          PASSWORD=${{ vars.PASSWORD }}
          UUID=${{ vars.UUID }}
          PATH_VLESS=${{ vars.PATH_VLESS }}
          PATH_VMESS=${{ vars.PATH_VMESS }}
          WARP_SERVER=${{ vars.WARP_SERVER }}
          WARP_KEY=${{ vars.WARP_KEY }}
          TUNNEL=${{ vars.TUNNEL }}
